"""ML dose-surrogate scaffolding (optional torch dependency).

A learned depth-dose surrogate (e.g. a DoTA/ADoTA-style transformer) is a later
benchmark target, not a first implementation. This module defines the data
schema the SDE/OpenGATE branches should emit for training, and guards the torch
import so the core package stays dependency-light.

Keep model inputs explicit: material/density profile, beam energy, energy
spread, voxel spacing, and RNG seed. A surrogate must always ship with
deterministic reference checks and an uncertainty flag before any comparison is
trusted -- neural dose engines fail silently out of distribution.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from .transport import DepthDose


def torch_available() -> bool:
    """True if the optional ``torch`` package can be imported."""
    try:
        import torch  # noqa: F401
    except Exception:
        return False
    return True


@dataclass
class SurrogateSample:
    """One training example: input geometry/beam -> target depth-dose.

    Fields are explicit and unit-tagged so datasets generated by the SDE and
    OpenGATE branches are interchangeable and never silently rescaled.
    """

    density_profile_g_cm3: NDArray[np.float64]  # per-voxel density along depth
    rsp_profile: NDArray[np.float64]            # per-voxel relative stopping power
    energy_mev: float
    energy_spread_pct: float
    dz_cm: float
    target_dose: NDArray[np.float64]            # MeV/g per voxel
    seed: int


def sample_from_depth_dose(result: DepthDose, rsp_profile: NDArray[np.float64]) -> SurrogateSample:
    """Build a training sample from a simulated depth-dose result."""
    meta = result.metadata
    densities = np.array([s["density_g_cm3"] for s in meta["slabs"]])
    # Broadcast slab densities onto the voxel grid is caller-specific; here we
    # store the first-slab density as a placeholder profile length.
    density_profile = np.full_like(result.z_cm, densities[0])
    return SurrogateSample(
        density_profile_g_cm3=density_profile,
        rsp_profile=np.asarray(rsp_profile, dtype=np.float64),
        energy_mev=float(meta["initial_energy_mev"]),
        energy_spread_pct=float(meta.get("energy_spread_pct", 0.0)),
        dz_cm=float(meta["dz_cm"]),
        target_dose=result.dose.copy(),
        seed=int(meta.get("seed", 0)),
    )
