"""Validate predicted LETd against the braggpeak held-out LETd reference.

The reference is the held-out ``letd`` HDF5 target generated by braggpeak. If a
legacy file lacks that dataset, the script falls back to a CSDA LET proxy from
raw density and mass-stopping prior channels:

    LETd [keV/um] = density [g/cm^3] * mass stopping [MeV cm^2/g] * 1000 / 10000
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import torch

from braggpeak.units import KEV_PER_MEV, UM_PER_CM
from braggtransporter.config import get_device
from braggtransporter.evaluate import load_model


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ckpt", default="experiments/bt/braggtransporter_v0/best.pt")
    parser.add_argument("--data", default="data/generated/phase1_1d.h5")
    parser.add_argument("--split", default="heldout_energy")
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--out", default="docs/results/phase3_letd.csv")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows, corr, mae = validate_letd(
        ckpt_path=Path(args.ckpt),
        data_path=Path(args.data),
        split=args.split,
        batch_size=args.batch_size,
        device_name=args.device,
    )
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {out_path}")
    print(f"LETd Pearson correlation: {corr:.6f}")
    print(f"LETd mean abs error: {mae:.6f} keV/um")


def validate_letd(
    *,
    ckpt_path: Path,
    data_path: Path,
    split: str,
    batch_size: int,
    device_name: str,
) -> tuple[list[dict[str, float | int | str]], float, float]:
    device = get_device(device_name)
    model = load_model(ckpt_path, device_name)
    rows: list[dict[str, float | int | str]] = []
    pred_all: list[np.ndarray] = []
    ref_all: list[np.ndarray] = []

    with h5py.File(data_path, "r") as h5:
        group = _choose_group(h5, split)
        x_mean, x_std, scalar_mean, scalar_std = _norm_stats(h5)
        n = int(group["x"].shape[0])
        for start in range(0, n, batch_size):
            stop = min(start + batch_size, n)
            x_raw = np.asarray(group["x"][start:stop], dtype=np.float32)
            scalars_raw = np.asarray(group["scalars"][start:stop], dtype=np.float32)
            z = np.asarray(group["z"][start:stop], dtype=np.float32)
            ref = _reference_letd(group, start, stop, x_raw)
            energy = _energy_mev(group, scalars_raw, start, stop)

            x = (x_raw - x_mean) / x_std
            scalars = (scalars_raw - scalar_mean) / scalar_std
            with torch.no_grad():
                out = model(
                    torch.as_tensor(x, dtype=torch.float32, device=device),
                    torch.as_tensor(scalars, dtype=torch.float32, device=device),
                )
            if "letd" not in out:
                raise ValueError(f"Checkpoint {ckpt_path} did not return a 'letd' prediction.")
            pred = out["letd"].detach().cpu().numpy().astype(np.float64)

            pred_all.append(pred.reshape(-1))
            ref_all.append(ref.reshape(-1))
            for local_i in range(pred.shape[0]):
                sample_idx = start + local_i
                valid = np.isfinite(pred[local_i]) & np.isfinite(ref[local_i])
                sample_mae = float(np.mean(np.abs(pred[local_i][valid] - ref[local_i][valid]))) if np.any(valid) else float("nan")
                for j in range(pred.shape[1]):
                    rows.append(
                        {
                            "sample_index": int(sample_idx),
                            "energy_mev": float(energy[local_i]),
                            "z_cm": float(z[local_i, j]),
                            "pred_letd_kev_um": float(pred[local_i, j]),
                            "ref_letd_kev_um": float(ref[local_i, j]),
                            "abs_error_kev_um": float(abs(pred[local_i, j] - ref[local_i, j])),
                            "sample_mae_kev_um": sample_mae,
                            "reference": "braggpeak_hdf5_letd" if "letd" in group else "braggpeak_csda_stopping_proxy",
                        }
                    )

    pred_flat = np.concatenate(pred_all)
    ref_flat = np.concatenate(ref_all)
    valid = np.isfinite(pred_flat) & np.isfinite(ref_flat)
    if valid.sum() < 2:
        corr = float("nan")
    else:
        corr = float(np.corrcoef(pred_flat[valid], ref_flat[valid])[0, 1])
    mae = float(np.mean(np.abs(pred_flat[valid] - ref_flat[valid]))) if np.any(valid) else float("nan")
    return rows, corr, mae


def _choose_group(h5: Any, requested: str) -> Any:
    if requested in h5:
        return h5[requested]
    for name in ("heldout_energy", "heldout", "test", "val", "validation"):
        if name in h5:
            return h5[name]
    raise KeyError(f"No held-out-like split found in {h5.filename}.")


def _norm_stats(h5: Any) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    if "norm" not in h5:
        return (
            np.asarray(0.0, dtype=np.float32),
            np.asarray(1.0, dtype=np.float32),
            np.asarray(0.0, dtype=np.float32),
            np.asarray(1.0, dtype=np.float32),
        )
    return (
        np.asarray(h5["norm/x_mean"][...], dtype=np.float32),
        np.asarray(h5["norm/x_std"][...], dtype=np.float32),
        np.asarray(h5["norm/scalar_mean"][...], dtype=np.float32),
        np.asarray(h5["norm/scalar_std"][...], dtype=np.float32),
    )


def _reference_letd(group: Any, start: int, stop: int, x_raw: np.ndarray) -> np.ndarray:
    if "letd" in group:
        return np.asarray(group["letd"][start:stop], dtype=np.float64)
    density = x_raw[..., 0].astype(np.float64)
    mass_stopping = x_raw[..., 5].astype(np.float64)
    return np.maximum(density * mass_stopping * KEV_PER_MEV / UM_PER_CM, 0.0)


def _energy_mev(group: Any, scalars_raw: np.ndarray, start: int, stop: int) -> np.ndarray:
    if "energy_mev" in group:
        return np.asarray(group["energy_mev"][start:stop], dtype=np.float64)
    return scalars_raw[:, 0].astype(np.float64)


if __name__ == "__main__":
    main()
